// ─────────────────────────────────────────────────────────────────────────────
// JSON ↔ TypeScript Interface
// ─────────────────────────────────────────────────────────────────────────────

interface TsInferenceContext {
  interfaces: Map<string, string>; // name → body
  nameCounter: Map<string, number>; // base name → next suffix
}

function tsTypeName(key: string, ctx: TsInferenceContext): string {
  // PascalCase the key, strip non-alphanumerics
  const base = key
    .replace(/[^a-zA-Z0-9]/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('') || 'Anon';
  const safeBase = /^[A-Za-z]/.test(base) ? base : `T${base}`;
  const count = ctx.nameCounter.get(safeBase) ?? 0;
  ctx.nameCounter.set(safeBase, count + 1);
  return count === 0 ? safeBase : `${safeBase}${count + 1}`;
}

function inferType(value: any, suggestedName: string, ctx: TsInferenceContext): string {
  if (value === null) return 'null';
  if (value === undefined) return 'undefined';
  const t = typeof value;
  if (t === 'string') return 'string';
  if (t === 'number') return 'number';
  if (t === 'boolean') return 'boolean';

  if (Array.isArray(value)) {
    if (value.length === 0) return 'unknown[]';
    // Infer the union of element types
    const elementTypes = new Set<string>();
    let hasObject = false;
    let mergedObject: Record<string, any> = {};
    let presenceCount: Record<string, number> = {};
    for (const item of value) {
      if (item !== null && typeof item === 'object' && !Array.isArray(item)) {
        hasObject = true;
        for (const k of Object.keys(item)) {
          mergedObject[k] = item[k];
          presenceCount[k] = (presenceCount[k] ?? 0) + 1;
        }
      } else {
        elementTypes.add(inferType(item, suggestedName, ctx));
      }
    }
    if (hasObject) {
      // Build a single interface from the merged object, marking optional keys
      const interfaceName = tsTypeName(singularize(suggestedName), ctx);
      buildInterfaceWithOptionals(interfaceName, mergedObject, presenceCount, value.length, ctx);
      elementTypes.add(interfaceName);
    }
    const types = Array.from(elementTypes);
    if (types.length === 1) return `${types[0]}[]`;
    return `(${types.join(' | ')})[]`;
  }

  if (t === 'object') {
    const interfaceName = tsTypeName(suggestedName, ctx);
    buildInterface(interfaceName, value, ctx);
    return interfaceName;
  }

  return 'unknown';
}

function buildInterface(name: string, obj: Record<string, any>, ctx: TsInferenceContext) {
  const lines: string[] = [];
  for (const key of Object.keys(obj)) {
    const value = obj[key];
    const fieldType = inferType(value, key, ctx);
    const safeKey = /^[A-Za-z_][A-Za-z0-9_]*$/.test(key) ? key : `"${key}"`;
    lines.push(`  ${safeKey}: ${fieldType};`);
  }
  ctx.interfaces.set(name, lines.join('\n'));
}

function buildInterfaceWithOptionals(
  name: string,
  obj: Record<string, any>,
  presenceCount: Record<string, number>,
  total: number,
  ctx: TsInferenceContext
) {
  const lines: string[] = [];
  for (const key of Object.keys(obj)) {
    const value = obj[key];
    const fieldType = inferType(value, key, ctx);
    const safeKey = /^[A-Za-z_][A-Za-z0-9_]*$/.test(key) ? key : `"${key}"`;
    const isOptional = (presenceCount[key] ?? 0) < total;
    const optionalMark = isOptional ? '?' : '';
    lines.push(`  ${safeKey}${optionalMark}: ${fieldType};`);
  }
  ctx.interfaces.set(name, lines.join('\n'));
}

function singularize(plural: string): string {
  // Naive English singularization for naming inferred element types
  if (plural.endsWith('ies') && plural.length > 3) return plural.slice(0, -3) + 'y';
  if (plural.endsWith('ses') && plural.length > 3) return plural.slice(0, -2);
  if (plural.endsWith('s') && plural.length > 1) return plural.slice(0, -1);
  return plural;
}

export function jsonToTypeScript(parsed: any, rootName = 'Root'): string {
  const ctx: TsInferenceContext = {
    interfaces: new Map(),
    nameCounter: new Map(),
  };
  // Force the root to use the provided name
  if (Array.isArray(parsed)) {
    const elementType = inferType(parsed, rootName, ctx);
    return `// Generated by DoItSwift JSON Formatter\nexport type ${rootName} = ${elementType};\n\n${formatInterfaces(ctx)}`;
  }
  if (parsed === null || typeof parsed !== 'object') {
    const t = inferType(parsed, rootName, ctx);
    return `// Generated by DoItSwift JSON Formatter\nexport type ${rootName} = ${t};\n`;
  }
  // Object root — name it explicitly
  ctx.nameCounter.set(rootName, 1);
  buildInterface(rootName, parsed, ctx);
  return `// Generated by DoItSwift JSON Formatter\n\n${formatInterfaces(ctx)}`;
}

function formatInterfaces(ctx: TsInferenceContext): string {
  const out: string[] = [];
  for (const [name, body] of ctx.interfaces) {
    out.push(`export interface ${name} {\n${body}\n}`);
  }
  return out.join('\n\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// JSON ↔ CSV
// ─────────────────────────────────────────────────────────────────────────────

function flatten(obj: any, prefix = '', result: Record<string, any> = {}): Record<string, any> {
  if (obj === null || typeof obj !== 'object') {
    result[prefix || 'value'] = obj;
    return result;
  }
  if (Array.isArray(obj)) {
    // For arrays inside a row, JSON-stringify them to a single cell
    result[prefix || 'value'] = JSON.stringify(obj);
    return result;
  }
  for (const key of Object.keys(obj)) {
    const newKey = prefix ? `${prefix}.${key}` : key;
    const value = obj[key];
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      flatten(value, newKey, result);
    } else if (Array.isArray(value)) {
      result[newKey] = JSON.stringify(value);
    } else {
      result[newKey] = value;
    }
  }
  return result;
}

function escapeCsvCell(value: any): string {
  if (value === null || value === undefined) return '';
  const str = typeof value === 'string' ? value : String(value);
  // Escape if contains comma, double-quote, newline, or carriage return
  if (/[",\n\r]/.test(str)) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export function jsonToCsv(parsed: any): string {
  // Normalize input to an array of rows
  let rows: any[];
  if (Array.isArray(parsed)) {
    rows = parsed;
  } else if (parsed !== null && typeof parsed === 'object') {
    rows = [parsed];
  } else {
    // Primitive — single column, single row
    return `value\n${escapeCsvCell(parsed)}`;
  }

  if (rows.length === 0) return '';

  // Flatten every row and collect all unique column keys
  const flatRows = rows.map((r) => flatten(r));
  const columnSet = new Set<string>();
  for (const row of flatRows) {
    for (const key of Object.keys(row)) columnSet.add(key);
  }
  const columns = Array.from(columnSet);

  const headerLine = columns.map((c) => escapeCsvCell(c)).join(',');
  const bodyLines = flatRows.map((row) => columns.map((col) => escapeCsvCell(row[col])).join(','));
  return [headerLine, ...bodyLines].join('\n');
}

// CSV → JSON: parse RFC 4180-style CSV and produce array of objects
function parseCsvLine(line: string): string[] {
  const cells: string[] = [];
  let current = '';
  let inQuotes = false;
  let i = 0;
  while (i < line.length) {
    const c = line[i];
    if (inQuotes) {
      if (c === '"') {
        if (line[i + 1] === '"') {
          current += '"';
          i += 2;
        } else {
          inQuotes = false;
          i++;
        }
      } else {
        current += c;
        i++;
      }
    } else {
      if (c === ',') {
        cells.push(current);
        current = '';
        i++;
      } else if (c === '"' && current === '') {
        inQuotes = true;
        i++;
      } else {
        current += c;
        i++;
      }
    }
  }
  cells.push(current);
  return cells;
}

function splitCsvRows(input: string): string[] {
  // Split on \n but respect quoted strings that contain newlines
  const rows: string[] = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < input.length; i++) {
    const c = input[i];
    if (c === '"') {
      // Toggle quote state, but handle escaped ""
      if (inQuotes && input[i + 1] === '"') {
        current += '""';
        i++;
        continue;
      }
      inQuotes = !inQuotes;
      current += c;
    } else if ((c === '\n' || c === '\r') && !inQuotes) {
      if (c === '\r' && input[i + 1] === '\n') i++; // skip \r\n
      if (current) rows.push(current);
      current = '';
    } else {
      current += c;
    }
  }
  if (current) rows.push(current);
  return rows;
}

function inferCellValue(s: string): any {
  if (s === '') return null;
  if (s === 'true') return true;
  if (s === 'false') return false;
  if (s === 'null') return null;
  // Number?
  if (/^-?\d+(\.\d+)?([eE][+-]?\d+)?$/.test(s)) {
    const n = Number(s);
    if (!Number.isNaN(n)) return n;
  }
  // JSON value? (array or object stored as string)
  if ((s.startsWith('[') && s.endsWith(']')) || (s.startsWith('{') && s.endsWith('}'))) {
    try {
      return JSON.parse(s);
    } catch {
      /* fallthrough */
    }
  }
  return s;
}

export function csvToJson(input: string): any[] {
  const rows = splitCsvRows(input.trim());
  if (rows.length === 0) return [];
  const headers = parseCsvLine(rows[0]);
  const result: any[] = [];
  for (let r = 1; r < rows.length; r++) {
    const cells = parseCsvLine(rows[r]);
    const obj: Record<string, any> = {};
    for (let c = 0; c < headers.length; c++) {
      const key = headers[c];
      const raw = cells[c] ?? '';
      // Reconstruct nested objects from dot-notation keys
      assignDotPath(obj, key, inferCellValue(raw));
    }
    result.push(obj);
  }
  return result;
}

function assignDotPath(obj: Record<string, any>, path: string, value: any) {
  const parts = path.split('.');
  let cursor = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    const part = parts[i];
    if (typeof cursor[part] !== 'object' || cursor[part] === null) {
      cursor[part] = {};
    }
    cursor = cursor[part];
  }
  cursor[parts[parts.length - 1]] = value;
}

// ─────────────────────────────────────────────────────────────────────────────
// JSON ↔ YAML
// ─────────────────────────────────────────────────────────────────────────────

function yamlIndent(level: number): string {
  return '  '.repeat(level);
}

function needsYamlQuoting(s: string): boolean {
  if (s === '') return true;
  if (/^(true|false|null|yes|no|on|off|~)$/i.test(s)) return true;
  if (/^-?\d+(\.\d+)?([eE][+-]?\d+)?$/.test(s)) return true;
  if (/[:#&*!|>'"%@`{}\[\],]|^\s|\s$|\n|\t/.test(s)) return true;
  if (/^[\s-?]/.test(s)) return true;
  return false;
}

function yamlEscapeDouble(s: string): string {
  return (
    '"' +
    s
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\t/g, '\\t')
      .replace(/\r/g, '\\r') +
    '"'
  );
}

function yamlValue(value: any, level: number): string {
  if (value === null) return 'null';
  if (value === undefined) return 'null';
  if (typeof value === 'boolean') return String(value);
  if (typeof value === 'number') {
    if (!isFinite(value)) return '.inf';
    if (Number.isNaN(value)) return '.nan';
    return String(value);
  }
  if (typeof value === 'string') {
    if (value.includes('\n')) {
      // Use literal block scalar for multi-line strings
      const lines = value.split('\n');
      return '|\n' + lines.map((l) => yamlIndent(level + 1) + l).join('\n');
    }
    if (needsYamlQuoting(value)) return yamlEscapeDouble(value);
    return value;
  }
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    return (
      '\n' +
      value
        .map((item) => {
          const rendered = yamlValue(item, level + 1);
          if (typeof item === 'object' && item !== null && !Array.isArray(item) && Object.keys(item).length > 0) {
            // Inline first key on the dash line
            const lines = rendered.trimStart().split('\n');
            return (
              yamlIndent(level + 1) +
              '- ' +
              lines[0] +
              (lines.length > 1 ? '\n' + lines.slice(1).map((l) => '  ' + l).join('\n') : '')
            );
          }
          return yamlIndent(level + 1) + '- ' + rendered;
        })
        .join('\n')
    );
  }
  if (typeof value === 'object') {
    const keys = Object.keys(value);
    if (keys.length === 0) return '{}';
    return (
      '\n' +
      keys
        .map((k) => {
          const child = value[k];
          const childRendered = yamlValue(child, level + 1);
          const safeKey = needsYamlQuoting(k) ? yamlEscapeDouble(k) : k;
          // Inline simple values, block-form complex values
          if (typeof child === 'object' && child !== null && (Array.isArray(child) ? child.length > 0 : Object.keys(child).length > 0)) {
            return yamlIndent(level + 1) + safeKey + ':' + childRendered;
          }
          return yamlIndent(level + 1) + safeKey + ': ' + childRendered;
        })
        .join('\n')
    );
  }
  return String(value);
}

export function jsonToYaml(parsed: any): string {
  if (parsed === null || typeof parsed !== 'object') {
    return yamlValue(parsed, 0) + '\n';
  }
  const rendered = yamlValue(parsed, -1).trimStart();
  return rendered + (rendered.endsWith('\n') ? '' : '\n');
}

// YAML → JSON: lightweight parser that handles common cases
// Supports: nested maps, flow/block sequences, scalars, quoted strings, comments
// Limitations: no anchors/aliases, no complex tags, no merge keys
export function yamlToJson(input: string): any {
  const lines = input.split('\n').map((l) => l).filter((l) => !/^\s*#/.test(l));
  // Strip trailing comments outside strings
  const cleaned = lines
    .map((l) => {
      let inSingle = false,
        inDouble = false;
      let result = '';
      for (let i = 0; i < l.length; i++) {
        const c = l[i];
        if (c === "'" && !inDouble) inSingle = !inSingle;
        else if (c === '"' && !inSingle) inDouble = !inDouble;
        if (c === '#' && !inSingle && !inDouble) break;
        result += c;
      }
      return result.trimEnd();
    })
    .filter((l) => l.trim().length > 0);

  if (cleaned.length === 0) return null;

  const { value } = parseYamlBlock(cleaned, 0, 0);
  return value;
}

function parseYamlBlock(lines: string[], startIdx: number, indent: number): { value: any; nextIdx: number } {
  if (startIdx >= lines.length) return { value: null, nextIdx: startIdx };

  const firstLine = lines[startIdx];
  const firstIndent = firstLine.search(/\S/);

  if (firstIndent < indent) return { value: null, nextIdx: startIdx };

  const trimmed = firstLine.trim();

  // Sequence (starts with -)
  if (trimmed.startsWith('- ') || trimmed === '-') {
    const result: any[] = [];
    let i = startIdx;
    while (i < lines.length) {
      const line = lines[i];
      const lineIndent = line.search(/\S/);
      if (lineIndent < firstIndent) break;
      if (lineIndent !== firstIndent) {
        i++;
        continue;
      }
      const t = line.trim();
      if (!t.startsWith('-')) break;
      const rest = t.length > 1 ? t.substring(2).trim() : '';
      if (rest === '' || rest.endsWith(':')) {
        // Next-line block
        const sub = parseYamlBlock(lines, i + 1, firstIndent + 2);
        if (rest.endsWith(':')) {
          // mapping in seq, single key with empty value -> handled by sub
          const key = rest.slice(0, -1).trim();
          result.push({ [key]: sub.value });
        } else {
          result.push(sub.value);
        }
        i = sub.nextIdx;
      } else if (rest.includes(':') && !isInlineFlow(rest)) {
        // Inline mapping start: e.g. "- key: value"
        const obj: Record<string, any> = {};
        const colonIdx = rest.indexOf(':');
        const key = rest.substring(0, colonIdx).trim();
        const val = rest.substring(colonIdx + 1).trim();
        if (val === '') {
          // continue with deeper-indented block
          const sub = parseYamlBlock(lines, i + 1, firstIndent + 2);
          obj[key] = sub.value;
          i = sub.nextIdx;
        } else {
          obj[key] = parseScalar(val);
          i++;
          // Look ahead for additional keys at firstIndent + 2
          while (i < lines.length) {
            const nextIndent = lines[i].search(/\S/);
            if (nextIndent !== firstIndent + 2) break;
            const nt = lines[i].trim();
            if (nt.startsWith('-')) break;
            const ci = nt.indexOf(':');
            if (ci === -1) break;
            const k2 = nt.substring(0, ci).trim();
            const v2 = nt.substring(ci + 1).trim();
            if (v2 === '') {
              const sub2 = parseYamlBlock(lines, i + 1, firstIndent + 4);
              obj[k2] = sub2.value;
              i = sub2.nextIdx;
            } else {
              obj[k2] = parseScalar(v2);
              i++;
            }
          }
        }
        result.push(obj);
      } else {
        // Inline scalar
        result.push(parseScalar(rest));
        i++;
      }
    }
    return { value: result, nextIdx: i };
  }

  // Mapping
  const result: Record<string, any> = {};
  let i = startIdx;
  while (i < lines.length) {
    const line = lines[i];
    const lineIndent = line.search(/\S/);
    if (lineIndent < firstIndent) break;
    if (lineIndent > firstIndent) {
      i++;
      continue;
    }
    const t = line.trim();
    const colonIdx = findKeyColonIndex(t);
    if (colonIdx === -1) {
      i++;
      continue;
    }
    const key = unquoteKey(t.substring(0, colonIdx).trim());
    const val = t.substring(colonIdx + 1).trim();
    if (val === '') {
      const sub = parseYamlBlock(lines, i + 1, firstIndent + 1);
      result[key] = sub.value;
      i = sub.nextIdx;
    } else {
      result[key] = parseScalar(val);
      i++;
    }
  }
  return { value: result, nextIdx: i };
}

function findKeyColonIndex(s: string): number {
  // First colon that's not inside quotes
  let inSingle = false,
    inDouble = false;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (c === "'" && !inDouble) inSingle = !inSingle;
    else if (c === '"' && !inSingle) inDouble = !inDouble;
    else if (c === ':' && !inSingle && !inDouble) return i;
  }
  return -1;
}

function unquoteKey(s: string): string {
  if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'"))) {
    return s.slice(1, -1);
  }
  return s;
}

function isInlineFlow(s: string): boolean {
  return /^\s*[\[{]/.test(s);
}

function parseScalar(s: string): any {
  s = s.trim();
  if (s === '' || s === '~' || s === 'null' || s === 'Null' || s === 'NULL') return null;
  if (s === 'true' || s === 'True' || s === 'TRUE' || s === 'yes' || s === 'Yes' || s === 'on' || s === 'On') return true;
  if (s === 'false' || s === 'False' || s === 'FALSE' || s === 'no' || s === 'No' || s === 'off' || s === 'Off') return false;
  // Quoted strings
  if (s.startsWith('"') && s.endsWith('"')) {
    return s
      .slice(1, -1)
      .replace(/\\n/g, '\n')
      .replace(/\\t/g, '\t')
      .replace(/\\"/g, '"')
      .replace(/\\\\/g, '\\');
  }
  if (s.startsWith("'") && s.endsWith("'")) {
    return s.slice(1, -1).replace(/''/g, "'");
  }
  // Inline flow (basic JSON-like)
  if ((s.startsWith('[') && s.endsWith(']')) || (s.startsWith('{') && s.endsWith('}'))) {
    try {
      return JSON.parse(s);
    } catch {
      /* fallthrough */
    }
  }
  // Number
  if (/^-?\d+$/.test(s)) return parseInt(s, 10);
  if (/^-?\d+\.\d+$/.test(s)) return parseFloat(s);
  if (/^-?\d+(\.\d+)?[eE][+-]?\d+$/.test(s)) return parseFloat(s);
  return s;
}
